# Generated by Django 4.2 on 2024-09-17 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingProblems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('sample_input', models.TextField()),
                ('sample_output', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_a', models.CharField(blank=True, max_length=1000, null=True)),
                ('option_b', models.CharField(blank=True, max_length=1000, null=True)),
                ('option_c', models.CharField(blank=True, max_length=1000, null=True)),
                ('option_d', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('answer', models.CharField(blank=True, choices=[(models.CharField(blank=True, max_length=1000, null=True), models.CharField(blank=True, max_length=1000, null=True)), (models.CharField(blank=True, max_length=1000, null=True), models.CharField(blank=True, max_length=1000, null=True)), (models.CharField(blank=True, max_length=1000, null=True), models.CharField(blank=True, max_length=1000, null=True)), (models.CharField(blank=True, max_length=1000, null=True), models.CharField(blank=True, max_length=1000, null=True))], max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseforCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz.codingproblems')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', multiselectfield.db.fields.MultiSelectField(choices=[('MCQ', 'Multiple Choice Questions'), ('Coding Task', 'Coding Task')], max_length=1000)),
                ('question', models.TextField()),
                ('option_a', models.CharField(blank=True, max_length=1000, null=True)),
                ('option_b', models.CharField(blank=True, max_length=1000, null=True)),
                ('option_c', models.CharField(blank=True, max_length=1000, null=True)),
                ('option_d', models.CharField(blank=True, max_length=1000, null=True)),
                ('coding_task_description', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, choices=[('python', 'python'), ('javascript', 'javascript'), ('java', 'java')], max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MCQSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(blank=True, choices=[('Option A', 'Option A'), ('Option B', 'Option B'), ('Option C', 'Option C'), ('Option D', 'Option D')], help_text='answer', max_length=350, null=True)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('mcq', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quizz.mcq')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mcq',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz.quiz'),
        ),
        migrations.CreateModel(
            name='CodingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_code', models.TextField()),
                ('result', models.BooleanField(default=True)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz.codingproblems')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='codingproblems',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz.quiz'),
        ),
    ]
