# Generated by Django 4.2 on 2024-09-17 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestCaseforCP',
            new_name='TestCaseForCodingProblem',
        ),
    ]
